// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: rqrs.proto

package rqrs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackClient is the client API for Back service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackClient interface {
	Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type backClient struct {
	cc grpc.ClientConnInterface
}

func NewBackClient(cc grpc.ClientConnInterface) BackClient {
	return &backClient{cc}
}

func (c *backClient) Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rqrs.Back/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackServer is the server API for Back service.
// All implementations must embed UnimplementedBackServer
// for forward compatibility
type BackServer interface {
	Do(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedBackServer()
}

// UnimplementedBackServer must be embedded to have forward compatible implementations.
type UnimplementedBackServer struct {
}

func (UnimplementedBackServer) Do(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedBackServer) mustEmbedUnimplementedBackServer() {}

// UnsafeBackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackServer will
// result in compilation errors.
type UnsafeBackServer interface {
	mustEmbedUnimplementedBackServer()
}

func RegisterBackServer(s grpc.ServiceRegistrar, srv BackServer) {
	s.RegisterService(&Back_ServiceDesc, srv)
}

func _Back_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rqrs.Back/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackServer).Do(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Back_ServiceDesc is the grpc.ServiceDesc for Back service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Back_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rqrs.Back",
	HandlerType: (*BackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Back_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rqrs.proto",
}
